//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace asmx.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListaEstudiante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListaEstudianteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreaEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreaEstudiante(string id, string nombre, string paterno, string materno, string fec_nac, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreaEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreaEstudianteAsync(string id, string nombre, string paterno, string materno, string fec_nac, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string eliminaEstudiante(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminaEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<string> eliminaEstudianteAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaEstudiante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editaEstudiante(string id, string nombre, string paterno, string materno, string fec_nac, string sexo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editaEstudiante", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editaEstudianteAsync(string id, string nombre, string paterno, string materno, string fec_nac, string sexo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : asmx.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<asmx.ServiceReference1.WebService1Soap>, asmx.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListaEstudiante() {
            return base.Channel.ListaEstudiante();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListaEstudianteAsync() {
            return base.Channel.ListaEstudianteAsync();
        }
        
        public string CreaEstudiante(string id, string nombre, string paterno, string materno, string fec_nac, string sexo) {
            return base.Channel.CreaEstudiante(id, nombre, paterno, materno, fec_nac, sexo);
        }
        
        public System.Threading.Tasks.Task<string> CreaEstudianteAsync(string id, string nombre, string paterno, string materno, string fec_nac, string sexo) {
            return base.Channel.CreaEstudianteAsync(id, nombre, paterno, materno, fec_nac, sexo);
        }
        
        public string eliminaEstudiante(string id) {
            return base.Channel.eliminaEstudiante(id);
        }
        
        public System.Threading.Tasks.Task<string> eliminaEstudianteAsync(string id) {
            return base.Channel.eliminaEstudianteAsync(id);
        }
        
        public string editaEstudiante(string id, string nombre, string paterno, string materno, string fec_nac, string sexo) {
            return base.Channel.editaEstudiante(id, nombre, paterno, materno, fec_nac, sexo);
        }
        
        public System.Threading.Tasks.Task<string> editaEstudianteAsync(string id, string nombre, string paterno, string materno, string fec_nac, string sexo) {
            return base.Channel.editaEstudianteAsync(id, nombre, paterno, materno, fec_nac, sexo);
        }
    }
}
